#!/bin/sh

sensors="$(sensors -j 2>/dev/null | grep -A3 fan1_input)"
cputemp=$(echo "$sensors" | awk 'END{print $2}')
fanrpm=$(echo "$sensors" | awk 'NR==1{print $2}')

echo " FAN:${fanrpm%.*}RPM |" > ~/.cache/statusbar/cpufan
echo " CPU:${cputemp%.*}°C |" > ~/.cache/statusbar/cputemp
