#!/bin/sh

if [ $# -eq 0 ]; then
	echo "No arguments supplied"
	echo 'use "up" or "down" as argument'
	exit

fi

if [ $1 = "up" ]; then
	rc-service mysql start
	rc-service apache2 start
fi

if [ $1 = "down" ]; then
	rc-service mysql stop
	rc-service apache2 stop
fi
