#!/bin/sh

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
	down) 	
		echo " WIFI DOWN |" > ~/.cache/statusbar/wifi;;
	up) 	
		strength=$(iw dev wlp3s0 station dump -v | grep signal: | awk '{print $2}')
		echo "$strength dBm |" > ~/.cache/statusbar/wifi;;
esac

